runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
  mime_type: text/css

- url: /images
  static_dir: images
  
- url: /.*
  script: mapit.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest